name: Rijit Cloud Storage CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List files
        run: ls -l

      - name: Display success message
        run: echo "CI Pipeline executed successfully for Rijit Cloud Storage App"
